First simple attempt at a Dockerfile
Really, really simple, obvious Dockerfile.  Didn't really expect it to
work, but it had to be tried.

Got a whole big list of errors that will need looking at:

Could not remove /etc/apache2/mods-enabled/ssl.load: Permission denied
chown: changing ownership of '/var/lib/snipeit/data/private_uploads': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/suppliers': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/models': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/departments': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/consumables': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/manufacturers': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/locations': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/avatars': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/accessories': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/components': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/companies': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/categories': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads/barcodes': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/data/uploads': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/dumps': Operation not permitted
chown: changing ownership of '/var/lib/snipeit/keys': Operation not permitted
cp: cannot create regular file '/var/www/html/database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php': Permission denied
cp: cannot create regular file '/var/www/html/database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php': Permission denied
cp: cannot create regular file '/var/www/html/database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php': Permission denied
cp: cannot create regular file '/var/www/html/database/migrations/2016_06_01_000004_create_oauth_clients_table.php': Permission denied
cp: cannot create regular file '/var/www/html/database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php': Permission denied
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 9, in <module>
    load_entry_point('supervisor==3.2.0', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 367, in main
    go(options)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 377, in go
    d.main()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 77, in main
    info_messages)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1388, in make_logger
    stdout = self.nodaemon,
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 346, in getLogger
    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 172, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/var/www/html/supervisord.log'